additionalArgs:
  - "--retries"
  - "3"
  - "--retry-delay"
  - "10"
  - "-k"
  - "(test_vid_extraction_on_first_party_xhr or test_header_based_logger_logs_on_first_party_requests)"

internalMockCollectorURL: "http://mock-collector-mock-collector:3001"
siteURL: "http://java-enforcer-sample-site:3000"

image:
  repository: localhost:5001/enforcer-spec-tests