language: java
sudo: false
install: mvn install
jdk:
- openjdk8

before_install:
- chmod +x ./deploy/before-deploy.sh
- chmod +x ./deploy/deploy.sh

script: mvn test -P !build-extras -B

install: mvn install -P !build-extras -Dmaven.javadoc.skip=true -B

after_success:
- ./deploy/before-deploy.sh
- ./deploy/deploy.sh

cache:
  directories:
    - ~/.m2/repository

env:
  global:
  - secure: kb6/j+5D8Lm/zYS0Zih1WHQ31oJ6eTPmPK8j4jTcIP13oVdM/JaF31IV13gT/ZJH5hj2OjRxpX0i3/54igH0L1tT7i9rLaIElR9eVq/IULB3jAF+og1hSVTUneyQ5ujYBYFNjNgeYORWOkSI/4y8XHsrl7ImeBXOsrkifZTEMNIIanw+o1HYpOvcMvFAxff9FYnT8nPqLJYSeMWebkvLVE4Yg3hAuiHhuDSpNg+BjIbMD7C7P+rCTr76ptN81xVNB+NXoUi6P9k0tPshOJ9cxsLdmeHaDbMoQjrj88brIOLuDYubBs7xjaRivK4q7C2M8GHau7J1tyLVqKk0UYNkyVWLm/qnrkTpTFXFNqSUQykKNJGQJ7bbUmQQUSDWEOAMfBA8b6RnQshSmk8n9nG76n9KhNZemoPOg1yTCcV1pV6rzu5OdmKgR+6YSD3QZXC5JGrK1oVapNwLcnZrgPcTAbIkAZblHYwnn4TNjvxDUVtGfVdC8bQYjx65vsarcH+lHrvwOTiiOPlFbBbRcAtuRFZgt44ADYmLxCqtiOUneaf6m/kEOezwx+PERPkFXCL8O2qRWQk6FbaoS08GXT0rrOo1j6Ad//7Z71N8CZj/FcC5FYiOR7gHGe6zM3SvmMpSHV0w4/LgoaW/AtqrMFqAdHNhN2AzdDsGTYhC1rDZI3s=
  - secure: Xnf+48Xvd1NMatd8AdS2/sqrJYyOTwTE+viy2NuDYzs0ikHCvgsvnR9bKX72DgygXy6E4xwfSaicJxqJXdvL3RpCpF4e+QA/6HUxt1Chd6xVwwhhFrUNHhnWmueiWps8CbDOG+tv3ss0RTrxWXNRzCqFxNCTWGUM3atiqg0I9eBa9F5w7MBjczZ/zacah7KfmSjWC/gS3bv8elTYaZ7cj0lOYTzrVqn0+2AE7gsRA+OxhHEwUE5c40hCuY0bxRnWkA2CpN4BVyDclpeL8QOwsoswyHl71W4ek30Ib6JHdmSiD6IBIXY2HXSGvZr06ZkM6n/h6OVUJ0+Wq59m2R0HRtG5cuS6OvROdPd7CH59hiOF/0HgPbn5G7BRVeWNFvk3jELZE3myZsE8R4+BKqCGWbjbUgXbF67l833VWu3R2DUVkQB/t3+LTg51cx+BtQusHIhMsa3abWU2YkmGD+qoA4MQsaVFVy0y1aiplyP1x4JjuPlhaJQvsMR0IBw8xZias1yfEg0Mac4vEiNxehn/bxe8JVTmrgbXJl2LOORPWmfvUA+xtTRRKrD2LIhRoXrb7OU/GaXfDyW6Rh7ZfpMge0ns41muXmsvOWG0nPsaJx2VJPEIvuExmiFxMQInsGU3IOx/1irVL2MD5YxI9/YgfO/r+E7WYP+49gwHJU6D8SI=
  - secure: LYb1wrNJgll/KTFUaQ5yecSmNLEpKCvXBh3Qmt9WIdxUshnb9nKMzbrea/fVv/OW7XCiAyCKL4kpX7CWMlFdo5lGUJLVv7NlYkWoZRwaRY4epjJ3JEqjtgzbUUnw9e4rtlMMG9Oa+vTJpcH3ip4sTNrMhm9WxcmyuE/OaZgnsy2cpYris8Q0rdeTVCDtB4MC7xId6th2NQYBvNamjC9XJwWBkQ7B3uzIuzHmrQuhvtvhmZ2D+3N6AmfQ6AN763NTI0ejpoe4y2Mafsqdtf903+7dpnVFCmEruw6lfqvKu3T2CMjHmVtt3UP7cH1dUPEN9vnaJsBuOuLKRd+/j+L1ZLy4GQXaNHKRccJGa1CJZbGUX1HX6V7TF1kc2eobIi0yKAZ70X3r4IyUqQFrrev3PLOVy+ory2f/nlXDGQQJDcwSO83Tp+aReKa4cW/2V10fzG2PWpQOGw+8t1sCSckC92pBMbNk30nPTLsduWLokHRE5NanZQ9JNeO1mlSG/mo4rhdHymjPSebBT2D4xXlu08CPT92m8AZgo93+irfHeNyhid+XhXGzLF3IWsQfono3YrzZ5X3959veF4dT3cNRM6aksS+HB1UsMKU9rwaoKbotd+x47ana1bxfV2J6HOAycwcmOj3GHoYqXpbWyinxgjX8qpZajMnH6Yx8QAA2Q+U=
  - secure: J/y0a5W2TNxIQD5rUiyRUrSYGJgM27Bog2NW7Sy/Xczb9qYfKHmqd3l9jvuh4uMkRYAVY0n7TWkaQjmSWmyAiWcNRYR0EYFyreAbkswyTcvK2fO0cT9G11HftVXazYRa0zpLgxOJoDittS5RTZ6/KzKf1Yh9gKahzetn/MvxiOXOD4V6WRGY4yWmqHETuJhZvV8lDm2cfvorDTMWm1Tr7pa7KdtiDL/Z7Pxqehq/sGyhITZQyjTLQEB6MEDfTNQ+c//7EJ9OqOrb5jDTQTw3CTxVQvrVrt5AJbE8GGFa4xRE2yR9H1DRsw+lgzj5DLlIZlk/kxXEfJcauVDgOQx1x7A/0S9VIPp8HwDOsFvjCRadRMXz4HnnZk+DB1JIZ/duKiZgnrkD7OVdMDFt4l4LmfQjV+U9ZnxKh3schTSXnQ5avoUm4s7BnPnYhd/EBH8LNdEHsx4FMsNQGfow7yfRetR/TWvUij1VxNpkghIZl7YM3NihPMLbCzw9lJ1CeAb5pXet0FaKp1SQdhx5Y6oLlsdQfaW3UQYPdC0JklSzY5Tms9+iR/Pu6mlGJkQz6NCLz0Y1IxHN4R7QYxh1U3F4FM5U9UM2YtuOsfJzTS5ZK3GZO9oEo18kcmkHYHgyRWUETTIYw7j8OJeENGhSJiIyDNfUP5nc7vk9n5OvtF+jjsE=
